#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".
if [[ `python -m unittest discover tests` ]]
then
	echo "> Tests DID NOT pass !"
	exit 1
else
	echo "> Tests passed !"
fi

echo "Ready to commit !"
exit 0
